### ISSUE TITLE
Persona Import Blocking SwiftUI Environment Variables

### ISSUE THREAD

**Issue by noahbino** [persona-id/persona-ios-sdk#8]
`import Persona2` is causing build errors on `@Environment(\.presentationMode) var presentationMode`. When removing 1 the other works. 

Full error : `'Environment' is ambiguous for type lookup in this context`

**Comment by jacoblange-dev** [comment]
Sorry, you'll need to fully qualify usages of Environment since the name clashes with our Environment type. e.g. `@SwiftUI.Environment(\.presentationMode) var presentationMode`

**Comment by noahbino** [comment]
got it. Any plans on adding any native SwiftUI stuff in the future?

**Comment by jacoblange-dev** [comment]
Not at the moment but I'll note the interest, you can view a sample of how to integrate here https://stackoverflow.com/questions/73758537/integrating-persona-sdk-in-a-swiftui-view/73821670#73821670
